/Users/jezberg/Documents/Public-Solvers/loandra/Encoder.o /Users/jezberg/Documents/Public-Solvers/loandra/Encoder.or /Users/jezberg/Documents/Public-Solvers/loandra/Encoder.od /Users/jezberg/Documents/Public-Solvers/loandra/Encoder.op: /Users/jezberg/Documents/Public-Solvers/loandra/Encoder.cc \
  /Users/jezberg/Documents/Public-Solvers/loandra/Encoder.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/ParseUtils.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Constants.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Clone.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverStats.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_CNetworks.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Encodings.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/../MaxTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_GTE.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_Ladder.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_MTotalizer.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_SWC.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_Totalizer.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_Adder.h
/Users/jezberg/Documents/Public-Solvers/loandra/Main.o /Users/jezberg/Documents/Public-Solvers/loandra/Main.or /Users/jezberg/Documents/Public-Solvers/loandra/Main.od /Users/jezberg/Documents/Public-Solvers/loandra/Main.op: /Users/jezberg/Documents/Public-Solvers/loandra/Main.cc \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/ParseUtils.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/System.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Constants.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Clone.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverStats.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/FormulaPB.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/preprocessorinterface.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/preprocessor.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/global.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/preprocessedinstance.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/probleminstance.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/clause.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/touchedlist.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/trace.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/timer.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/log.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/AMSLEX.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/satsolverinterface.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/glucose3.cpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/../mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/../mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/../mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../utils/../mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../utils/../mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../core/Constants.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/ParserMaxSAT.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/algorithms/Alg_OLL_ITER.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/algorithms/../Encoder.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_CNetworks.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Encodings.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/../MaxTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_GTE.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_Ladder.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_MTotalizer.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_SWC.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_Totalizer.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/encodings/Enc_Adder.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/algorithms/../MaxSAT.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/algorithms/../maxpre2/src/preprocessorinterface.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/algorithms/Alg_CBLIN.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/algorithms/../MaxTypes.h
/Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.o /Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.or /Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.od /Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.op: /Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.cc \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSAT.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/ParseUtils.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Constants.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Clone.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverStats.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/FormulaPB.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/System.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/preprocessorinterface.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/preprocessor.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/global.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/preprocessedinstance.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/probleminstance.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/clause.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/touchedlist.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/trace.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/timer.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/log.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/AMSLEX.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/satsolverinterface.hpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/glucose3.cpp \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/../mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/../mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/../mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../utils/../mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../utils/../mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/maxpre2/src/satsolver/solvers/glucose3/core/../core/Constants.h
/Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.o /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.or /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.od /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.op: \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.cc \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/ParseUtils.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Constants.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Clone.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverStats.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/FormulaPB.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxTypes.h
/Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.o /Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.or /Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.od /Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.op: /Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.cc \
  /Users/jezberg/Documents/Public-Solvers/loandra/ParserPB.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxSATFormula.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Solver.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Heap.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Vec.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/IntTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/XAlloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alg.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/Options.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/utils/ParseUtils.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverTypes.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Map.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Alloc.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/BoundedQueue.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/Constants.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/mtl/Clone.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/solvers/glucose4.1/core/SolverStats.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/FormulaPB.h \
  /Users/jezberg/Documents/Public-Solvers/loandra/MaxTypes.h
